<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.cg.addressbook.TestAddressBook" tests="1" skipped="0" failures="0" errors="0" timestamp="2020-11-05T14:37:15" hostname="ABHINAVs-MacBook-Air.local" time="0.344">
  <properties/>
  <testcase name="given3Records_WhenSuccessfullyAddedToDB_ShouldReturnCorrectCount" classname="com.cg.addressbook.TestAddressBook" time="0.344"/>
  <system-out><![CDATA[Driver loaded
 com.mysql.jdbc.Driver
 com.mysql.fabric.jdbc.FabricMySQLDriver
Connecting to database:jdbc:mysql://localhost:3306/address_book_service?useSSL=false
Connected com.mysql.jdbc.JDBC4Connection@7ec0203c
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
